app:
  scheduler:
    enable: true
    interval: 10s
    delay: 10s

  url:
    gitHubBaseUrl: https://api.github.com/repos/
    stackOverflowBaseUrl: https://api.stackexchange.com/2.3/questions/

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
