app:
  scheduler:
    enable: true
    interval: 10s
    delay: 10s
  url:
    gitHubBaseUrl: https://api.github.com/repos/
    stackOverflowBaseUrl: https://api.stackexchange.com/2.3/questions/
    botBaseUrl: http://localhost:8090
  database-access-type: jdbc

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    liquibase:
      enabled: false
server:
  port: 8080
logging:
  config: classpath:log4j2-plain.xml
springdoc:
  swagger-ui:
    path: /swagger-ui

data-source:
  url: jdbc:postgresql://localhost:5432/scrapper
  username: postgres
  password: postgres

